import { IInvoiceRepository } from '../../domain/repositories/IInvoiceRepository';
import { IProjectPriceRepository } from '../../domain/repositories/IProjectPriceRepository';
import { Invoice } from '../../domain/entities/Invoice';
import { NotFoundError, ForbiddenError, ConflictError } from '../../shared/errors';

export class CreateInvoice {
  constructor(
    private invoiceRepo: IInvoiceRepository,
    private projectPriceRepo: IProjectPriceRepository
  ) {}

  async execute(
    userId: number,
    data: {
      project_id: number;
      client_name: string;
      client_email: string;
      client_location: string;
      invoice_date?: Date;
    }
  ): Promise<Invoice> {
    // Verify the project exists
    const project = await this.projectPriceRepo.findById(data.project_id);
    if (!project) {
      throw new NotFoundError('Project');
    }

    // Verify the project belongs to the authenticated user
    if (project.user_id !== userId) {
      throw new ForbiddenError('You do not have permission to create an invoice for this project');
    }

    // Check if an invoice already exists for this project
    const existingInvoice = await this.invoiceRepo.findByProjectId(data.project_id);
    if (existingInvoice) {
      throw new ConflictError('An invoice already exists for this project');
    }

    // Generate invoice number: INV-YYYYMMDD-{projectId}
    const now = new Date();
    const invoiceDate = data.invoice_date ?? now;
    const dateStr = invoiceDate.toISOString().slice(0, 10).replace(/-/g, '');
    const invoiceNumber = `INV-${dateStr}-${data.project_id}`;

    // Create the invoice entity
    const invoice = new Invoice(
      0, // auto-generated by DB
      invoiceNumber,
      data.project_id,
      data.client_name,
      data.client_email,
      data.client_location,
      data.invoice_date || now
    );

    return this.invoiceRepo.create(invoice);
  }
}
