import { IUserProfileRepository } from '../../domain/repositories/IUserProfileRepository';
import { UserProfile, SocialLink } from '../../domain/entities/UserProfile';

interface CreateUserProfileInput {
  user_id: number;
  bio?: string;
  skills?: string[];
  location?: string;
  profile_avatar?: string;
  experience_years?: number;
  seniority_level?: 'junior' | 'mid' | 'senior' | 'expert';
  social_links?: SocialLink[];
}

export class CreateUserProfile {
  constructor(private userProfileRepo: IUserProfileRepository) {}

  async execute(input: CreateUserProfileInput): Promise<UserProfile> {
    // Check if profile already exists
    const existingProfile = await this.userProfileRepo.findByUserId(input.user_id);
    if (existingProfile) {
      throw new Error('User profile already exists');
    }

    const profile = new UserProfile(
      0, // profile_id will be generated by the database
      input.user_id,
      input.bio,
      input.skills,
      input.location,
      input.profile_avatar,
      undefined,
      input.experience_years,
      input.seniority_level,
      input.social_links
    );

    return await this.userProfileRepo.create(profile);
  }
}